### ISSUE TITLE
Project status - Tested?

### ISSUE THREAD

**Issue by samuk** [luni64/MicroMod_3.2#3]
Did you ever make/test these?

I have a project that requires a Teensy in Micromod format, just wondering if these could be fabbed cheaper than the 'official' ones?

This is the project: https://github.com/rosmo-robot/smartcar_shield/blob/master/README.md#smartcar-10-current

**Comment by luni64** [comment]
Yes, I made a couple of them.  The "official" ones are T4 based, mine are T3.1 based. If you want to save money I assume you'd need really high volume to compete with sparkFun's pricing.

**Comment by samuk** [comment]
Thanks, you are probably correct. Do you happen to remember how much the ones you made worked out to?

**Comment by luni64** [comment]
There is a link to a live costed BOM in the readme. IIRC it was about 15EUR when I did the build. I did the assmembly myself so I don't know what this would cost these days.

**Comment by samuk** [comment]
Thanks, will check the BOM
